### ISSUE TITLE
Collect other rulesets in this repo

### ISSUE THREAD

**Issue by SvanBoxel** [WeTransfer/eslint-config-wetransfer#10]
Up for discussion:

Eslint enables you to export different sets of rules within one eslint plugin. Github does this for example: https://github.com/github/eslint-plugin-github.

I like to do this as well, cause it enables us to only import the rules we need per project and make it future-proof. Take in mind this module become a plugin instead of a shareable config. 

My proposal is distinct normal JS and React rules to start with, so they can be imported as follows: 
```
// .eslintrc.json
{
  "extends": [
    "plugin:wetransfer/recommended",
    "plugin:wetransfer/react"
  ]
}

```

**Comment by arkaitzgarro** [comment]
This documentation refers to configs: https://eslint.org/docs/developer-guide/shareable-configs#sharing-multiple-configs

**Comment by SvanBoxel** [comment]
Perfect, then we don't have to transform this into a plugin.
